server:
  port: 8900

spring:
  application:
    name: turbine-aggergator

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

turbine:
  app-config: weather-app, datetime-app
  cluster-name-expression: "'default'"