server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LukePalt/scf-config-repository.git

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka
